services:
  - type: web
    name: simplerpc-web
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: TOKEN
        sync: false

